on: [push]

jobs:
  runTest:
    name: test for Jopi
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'

      - name: Installing Npn & Lerna & Yarn
        run: |
          # npm install
          npm install -g npm-cli-login
          echo '${{ secrets.NPM_PASSWORD }}'
          npm install --global lerna
          yarn install

      - name: Set Git config
        run: |
          git config --global user.email "nquiroga@navent.com"  
          git config --global user.name "matiasz8"

      - name: Iniciando Lerna
        run: lerna init

      - name: run yarn test
        run: yarn test

      - name: yarn Jest
        run: yarn jest --coverage

      - name: Login to npm
        run: |
          npm-cli-login -u ${{ secrets.NPM_USER }} -p '${{ secrets.NPM_PASSWORD }}' -e ${{ secrets.NPM_EMAIL }}

      - name: se posiciona en la ruta de bin
        run: cd node_modules/.bin

      - name: updetea los paquetes de lerna
        run: lerna version patch --yes

      - name: publica una nueva verion de jopi
        run: lerna publish from-package --yes
