on: [push]

jobs:
  runTest:
    name: test for Jopi
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v1
        with:
          node-version: 12
          #registry-url: https://www.npmjs.com/
          #scope: "@bsabatino"

      - name: npm install
        run: npm install

      - name: lerna install
        run: npm install --global lerna

      - name: iniciar lerna
        run: lerna init

      - name: instala yarn
        run: yarn install
      #- name: yarn coverage
      #  run: yarn run coverage -u
      - name: run yarn test
        run: yarn test

      - name: yarn Jest
        run: yarn jest --coverage

      - name: listar
        run: ls
