on: [push]

jobs:
  runTest:
    name: test for Jopi
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: node install
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
          scope: '@nquiroga'

      - name: Installing Npn & Lerna & Yarn
        run: |
          npm install
          npm install --global lerna
          # yarn install

      # - name: Iniciando Lerna
      #   run: lerna init

      #   - name: run yarn test
      #     run: yarn test

      #   - name: yarn Jest
      #     run: yarn jest --coverage

      - name: Listar tokens
        run: npm token
        env:
          NODE_AUTH_TOKEN: 66177afd-25d9-47d4-baf4-9f6376f00342
